service: ${opt:no}-sls-handson-step-functions
 
provider:
  name: aws
  runtime: java8
  timeout: 90
  profile: sls-handson

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters

package:
  individually: true
  exclude:
    - "**"

stepFunctions:
  stateMachines:
    slsHandsonMachine:
      definition:
        Comment: Serverless Framework Handson Step Function
        StartAt: FaceDetection
        States:
          FaceDetection:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${opt:no}-face-detection-${opt:stage}-put
            Next: Parallel
          Parallel:
            Type: Parallel
            Next: PersistMetadata
            ResultPath: "$.parallelResult"
            Branches:
            - StartAt: FaceIndex
              States:
                FaceIndex:
                  Type: Task
                  Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${opt:no}-face-index-${opt:stage}-put
                  End: true
            - StartAt: Thumbnail
              States:
                Thumbnail:
                  Type: Task
                  Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${opt:no}-thumbnail-${opt:stage}-put
                  End: true
          PersistMetadata:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${opt:no}-persist-metadata-${opt:stage}-put
            End: true

