service: ${opt:no}-sls-handson-step-functions
 
provider:
  name: aws
  runtime: java8
  timeout: 90
  profile: sls-handson
  role: 'arn:aws:iam::184619842885:role/RoleSlsHandson2017'

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters

package:
  individually: true
  exclude:
    - "**"

functions:
  faceDetectionFunc:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler
    package:
      include:
        - ../face-detection/target/aws-spring-cloud-function-maven-dev-aws.jar
  faceIndexFunc:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler
    package:
      include:
        - ../face-index/target/aws-spring-cloud-function-maven-dev-aws.jar

stepFunctions:
  stateMachines:
    slsHandsonMachine:
      definition:
        Comment: Serverless Framework Handson Step Function
        StartAt: FaceDetection
        States:
          FaceDetection:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${opt:no}-sls-handson-step-functions-${opt:stage}-faceDetectionFunc
            Next: FaceIndex
          FaceIndex:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${opt:no}-sls-handson-step-functions-${opt:stage}-faceIndexFunc
            End: true

